# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

env:
  NODE_ENV: testing
  PG_USER: ddx
  PG_PASSWORD: 110119
  PG_HOST: localhost
  PG_PORT: 5432
  PG_DATABASE: dd_note
  PORT: 8080
  testURL: postgres://ebcngfzavaeurg:8742049fe1e4df1504acba5eb3b55145639f80dc94d2cf41ac9a0b7c04b59191@ec2-3-213-66-35.compute-1.amazonaws.com:5432/d2ecbgmihk2hla

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
